name: App With Github Actions with ArgoCD

on:
  push:
    paths-ignore:
      - 'manifest/**'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Make application.properties
        run: |
          cd ./src/main/resources
          touch ./application.properties
          echo "${{ secrets.PROPERTIES }}" > ./application.properties
        shell: bash

      - name: Build with Maven
        run: mvn -B -DskipTests package --file pom.xml

      - name: Naming jar file
        run: mv ./target/*.jar ./target/app.jar

      - name: Check jar file
        run: ls ./target

      - uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./target/*.jar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.sha }}

      - uses: actions/checkout@v4
        with:
          repository: phc979/app-with-argocd
          ref: main
          token: ${{ secrets.TOKEN }}
      - name: Set up Image
        run: |
          cat ./manifest/argocd-app.yaml  # 결과 이전
          DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}"
          GITHUB_SHA="${{ github.sha }}"
          sed -i "s%image: ${DOCKERHUB_USERNAME}/app-with-argocd:[A-z0-9]*%image: ${DOCKERHUB_USERNAME}/app-with-argocd:${GITHUB_SHA}%" ./manifest/argocd-app.yaml
          cat ./manifest/argocd-app.yaml  # 결과 확인

      - name: Commit and push changes
        run: |
          git config --local user.email "parkhancheol97@gmail.com"
          git config --local user.name "phc979"
          git add .
          git commit -m "Update nginx image to latest"
          git push